[package]
name = "xiapi-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial_test = "0.5.1"

[build-dependencies]
bindgen = "0.59.1"
