name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:    
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Download xiapi
      run: wget https://www.ximea.com/downloads/recent/XIMEA_Linux_SP.tgz
    - name: Unpack xiapi
      run: tar -xzf XIMEA_Linux_SP.tgz && cd package
    - name: Install xiapi
      run: ./install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --skip open_close --skip set_param --skip xi_sample --verbose
  
